"""'add magic link tokens'

Revision ID: 22a5d4c4fc07
Revises: 27621d27c7e1
Create Date: 2026-10-07 20:59:03.340568

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "22a5d4c4fc07"
down_revision: str | None = "27621d27c7e1"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "magic_link_tokens",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("request_key", sa.String(length=64), nullable=False),
        sa.Column("email_hash", sa.String(length=64), nullable=False),
        sa.Column("requester_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("credential_hash", sa.String(length=64), nullable=True),
        sa.Column("expires_at", mealie.db.migration_types.NaiveDateTime(), nullable=False),
        sa.Column("consumed_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_key"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("magic_link_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_magic_link_tokens_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_magic_link_tokens_email_hash"), ["email_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_magic_link_tokens_requester_hash"), ["requester_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_magic_link_tokens_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("magic_link_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_magic_link_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_magic_link_tokens_requester_hash"))
        batch_op.drop_index(batch_op.f("ix_magic_link_tokens_email_hash"))
        batch_op.drop_index(batch_op.f("ix_magic_link_tokens_created_at"))

    op.drop_table("magic_link_tokens")
    # ### end Alembic commands ###
